### ISSUE TITLE
undefined method `class_name' for nil:NilClass

### ISSUE THREAD

**Issue by elalemanyo** [gregnavis/active_record_doctor#123]
Hi,
I'm not sure why, and it may be a specific bug in my repository, but I am getting this error:
```
NoMethodError: undefined method `class_name' for nil:NilClass
Did you mean?  class_eval
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/reflection.rb:1021:in `derive_class_name'
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/reflection.rb:166:in `class_name'
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/reflection.rb:793:in `klass'
/usr/local/bundle/bundler/gems/active_record_doctor-fc736812db04/lib/active_record_doctor/detectors/incorrect_dependent_option.rb:58:in `block (2 levels) in detect'
/usr/local/bundle/bundler/gems/active_record_doctor-fc736812db04/lib/active_record_doctor/detectors/incorrect_dependent_option.rb:51:in `each'
/usr/local/bundle/bundler/gems/active_record_doctor-fc736812db04/lib/active_record_doctor/detectors/incorrect_dependent_option.rb:51:in `block in detect'
/usr/local/bundle/bundler/gems/active_record_doctor-fc736812db04/lib/active_record_doctor/detectors/incorrect_dependent_option.rb:44:in `each'
/usr/local/bundle/bundler/gems/active_record_doctor-fc736812db04/lib/active_record_doctor/detectors/incorrect_dependent_option.rb:44:in `detect'
/usr/local/bundle/bundler/gems/active_record_doctor-fc736812db04/lib/active_record_doctor/detectors/base.rb:50:in `run'
/usr/local/bundle/bundler/gems/active_record_doctor-fc736812db04/lib/active_record_doctor/detectors/base.rb:17:in `run'
/usr/local/bundle/bundler/gems/active_record_doctor-fc736812db04/lib/active_record_doctor/runner.rb:15:in `block in run_one'
/usr/local/bundle/bundler/gems/active_record_doctor-fc736812db04/lib/active_record_doctor/errors.rb:5:in `handle_exception'
/usr/local/bundle/bundler/gems/active_record_doctor-fc736812db04/lib/active_record_doctor/runner.rb:14:in `run_one'
/usr/local/bundle/bundler/gems/active_record_doctor-fc736812db04/lib/active_record_doctor/runner.rb:26:in `block in run_all'
/usr/local/bundle/bundler/gems/active_record_doctor-fc736812db04/lib/active_record_doctor/runner.rb:25:in `each'
/usr/local/bundle/bundler/gems/active_record_doctor-fc736812db04/lib/active_record_doctor/runner.rb:25:in `run_all'
/usr/local/bundle/bundler/gems/active_record_doctor-fc736812db04/lib/active_record_doctor/rake/task.rb:60:in `block in define'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/rake:25:in `load'
/usr/local/bundle/bin/rake:25:in `<main>'
Tasks: TOP => active_record_doctor
```

The truth is that I don't have much of an idea how to start solving it.
Thank you very much

**Comment by fatkodima** [comment]
It would be helpful if you can provide a small reproduction app.

**Comment by elalemanyo** [comment]
@fatkodima How can I know where the problem is so that I can reproduce it in a simpler application? The application where I have the problem I can't share it 😬

**Comment by fatkodima** [comment]
Try to debug and localize the problem. 
Try comment/uncomment models one by one and run `bundle exec rake active_record_doctor:incorrect_dependent_option` to see when it fails and on which model class.

**Comment by fatkodima** [comment]
@elalemanyo Were you able to identify the problem?

**Comment by elalemanyo** [comment]
@fatkodima sorry, I haven't had time to debug. But it's on my list 😬 I would let you know

**Comment by ocarreterom** [comment]
I get the same error running `active_record_doctor:incorrect_dependent_option`, also adding all the tables to the `ignore_tables` config.

**Comment by fatkodima** [comment]
Was able to reproduce - https://github.com/gregnavis/active_record_doctor/pull/128.

**Comment by gregnavis** [comment]
I assume this was resolved as part of https://github.com/gregnavis/active_record_doctor/commit/def30ee5353e5877ac08d0150bac2b0d943d22df, so I'm closing this issue. @elalemanyo, @ocarreterom, if the problem persists then feel free to reopen the issue.
