### ISSUE TITLE
Exception on missing_presence_validation after the debug logging commit

### ISSUE THREAD

**Issue by texpert** [gregnavis/active_record_doctor#129]
This started happening after https://github.com/gregnavis/active_record_doctor/commit/9210a46b4cdebb649bfa3e134af598b52b5aa5c7

```
16:56 $ bundle exec rake active_record_doctor:missing_presence_validation --trace
** Invoke active_record_doctor:missing_presence_validation (first_time)
** Invoke active_record_doctor:setup (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute active_record_doctor:setup
** Execute active_record_doctor:missing_presence_validation
rake aborted!
TypeError: no implicit conversion of nil into String
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/postgresql/utils.rb:26:in `quote_ident'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/postgresql/utils.rb:26:in `quoted'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/postgresql/quoting.rb:58:in `quote_table_name'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/postgresql_adapter.rb:925:in `column_definitions'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/schema_statements.rb:116:in `columns'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/active_record_doctor-9210a46b4cde/lib/active_record_doctor/detectors/base.rb:222:in `block in each_attribute'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/active_record_doctor-9210a46b4cde/lib/active_record_doctor/logger/dummy.rb:7:in `log'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/active_record_doctor-9210a46b4cde/lib/active_record_doctor/detectors/base.rb:96:in `log'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/active_record_doctor-9210a46b4cde/lib/active_record_doctor/detectors/base.rb:221:in `each_attribute'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/active_record_doctor-9210a46b4cde/lib/active_record_doctor/detectors/missing_presence_validation.rb:27:in `block in detect'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/active_record_doctor-9210a46b4cde/lib/active_record_doctor/detectors/base.rb:187:in `block (3 levels) in each_model'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/active_record_doctor-9210a46b4cde/lib/active_record_doctor/logger/dummy.rb:7:in `log'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/active_record_doctor-9210a46b4cde/lib/active_record_doctor/detectors/base.rb:96:in `log'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/active_record_doctor-9210a46b4cde/lib/active_record_doctor/detectors/base.rb:186:in `block (2 levels) in each_model'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/active_record_doctor-9210a46b4cde/lib/active_record_doctor/detectors/base.rb:173:in `each'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/active_record_doctor-9210a46b4cde/lib/active_record_doctor/detectors/base.rb:173:in `block in each_model'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/active_record_doctor-9210a46b4cde/lib/active_record_doctor/logger/dummy.rb:7:in `log'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/active_record_doctor-9210a46b4cde/lib/active_record_doctor/detectors/base.rb:96:in `log'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/active_record_doctor-9210a46b4cde/lib/active_record_doctor/detectors/base.rb:172:in `each_model'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/active_record_doctor-9210a46b4cde/lib/active_record_doctor/detectors/missing_presence_validation.rb:26:in `detect'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/active_record_doctor-9210a46b4cde/lib/active_record_doctor/detectors/base.rb:53:in `block in run'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/active_record_doctor-9210a46b4cde/lib/active_record_doctor/logger/dummy.rb:7:in `log'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/active_record_doctor-9210a46b4cde/lib/active_record_doctor/detectors/base.rb:96:in `log'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/active_record_doctor-9210a46b4cde/lib/active_record_doctor/detectors/base.rb:49:in `run'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/active_record_doctor-9210a46b4cde/lib/active_record_doctor/detectors/base.rb:17:in `run'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/active_record_doctor-9210a46b4cde/lib/active_record_doctor/runner.rb:16:in `block in run_one'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/active_record_doctor-9210a46b4cde/lib/active_record_doctor/errors.rb:5:in `handle_exception'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/active_record_doctor-9210a46b4cde/lib/active_record_doctor/runner.rb:15:in `run_one'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/active_record_doctor-9210a46b4cde/lib/active_record_doctor/rake/task.rb:46:in `block (3 levels) in define'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/sentry-ruby-5.5.0/lib/sentry/rake.rb:26:in `execute'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
~/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
~/.asdf/installs/ruby/3.1.2/bin/rake:25:in `load'
~/.asdf/installs/ruby/3.1.2/bin/rake:25:in `<top (required)>'
~/.asdf/installs/bundler/2.3.13/lib/bundler/cli/exec.rb:58:in `load'
~/.asdf/installs/bundler/2.3.13/lib/bundler/cli/exec.rb:58:in `kernel_load'
~/.asdf/installs/bundler/2.3.13/lib/bundler/cli/exec.rb:23:in `run'
~/.asdf/installs/bundler/2.3.13/lib/bundler/cli.rb:483:in `exec'
~/.asdf/installs/bundler/2.3.13/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
~/.asdf/installs/bundler/2.3.13/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
~/.asdf/installs/bundler/2.3.13/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
~/.asdf/installs/bundler/2.3.13/lib/bundler/cli.rb:31:in `dispatch'
~/.asdf/installs/bundler/2.3.13/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
~/.asdf/installs/bundler/2.3.13/lib/bundler/cli.rb:25:in `start'
~/.asdf/installs/bundler/2.3.13/exe/bundle:48:in `block in <main>'
~/.asdf/installs/bundler/2.3.13/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
~/.asdf/installs/bundler/2.3.13/exe/bundle:36:in `<main>'
Tasks: TOP => active_record_doctor:missing_presence_validation
```

**Comment by gregnavis** [comment]
@texpert, thanks for the report! Could you post the output of the command below?

```
ACTIVE_RECORD_DOCTOR_DEBUG=true bundle exec rake active_record_doctor:missing_presence_validation
```

**Comment by texpert** [comment]
> ACTIVE_RECORD_DOCTOR_DEBUG=true

Sure, @gregnavis, here it is:

```
...
** Execute active_record_doctor:setup
** Execute active_record_doctor:missing_presence_validation
missing_presence_validation
  Iterating over Active Record models
    ApplicationRecord
      Iterating over attributes of ApplicationRecord
rake aborted!
...
# all the trace here...
```

**Comment by gregnavis** [comment]
Thank you. I'm able to reproduce it and will push a fix later today.

**Comment by gregnavis** [comment]
@texpert, I pushed a fix in https://github.com/gregnavis/active_record_doctor/commit/73c6f856ee8c59598410d00f6cc846c6139942d6. Could you test whether it works?

**Comment by texpert** [comment]
Works like a charm, @gregnavis, thank you!

Also, the `ApplicationRecord references a non-existent table or view named` doesn't appear anymore.

🍾
