### ISSUE TITLE
Error on missing_foreign_keys

### ISSUE THREAD

**Issue by zenspider** [gregnavis/active_record_doctor#13]
```
10343 % rake active_record_doctor:missing_foreign_keys
rake aborted!
NotImplementedError: foreign_keys is not implemented
<gems>/activerecord-5.0.3/lib/active_record/connection_adapters/abstract/schema_statements.rb:864:in `foreign_keys'
<gems>/active_record_doctor-1.4.1/lib/active_record_doctor/tasks/missing_foreign_keys.rb:48:in `foreign_key?'
<gems>/active_record_doctor-1.4.1/lib/active_record_doctor/tasks/missing_foreign_keys.rb:34:in `block (2 levels) in missing_foreign_keys'
<gems>/active_record_doctor-1.4.1/lib/active_record_doctor/tasks/missing_foreign_keys.rb:29:in `select'
<gems>/active_record_doctor-1.4.1/lib/active_record_doctor/tasks/missing_foreign_keys.rb:29:in `block in missing_foreign_keys'
<gems>/active_record_doctor-1.4.1/lib/active_record_doctor/tasks/missing_foreign_keys.rb:26:in `map'
<gems>/active_record_doctor-1.4.1/lib/active_record_doctor/tasks/missing_foreign_keys.rb:26:in `missing_foreign_keys'
<gems>/active_record_doctor-1.4.1/lib/active_record_doctor/tasks/missing_foreign_keys.rb:18:in `run'
<gems>/active_record_doctor-1.4.1/lib/active_record_doctor/tasks/missing_foreign_keys.rb:10:in `run'
<gems>/active_record_doctor-1.4.1/lib/tasks/active_record_doctor_tasks.rake:16:in `block (2 levels) in <top (required)>'
Tasks: TOP => active_record_doctor:missing_foreign_keys
(See full trace by running task with --trace)
10357 % 
```

**Comment by gregnavis** [comment]
Thank you for reporting, @zenspider! I'll look into this soon.

**Comment by gregnavis** [comment]
@zenspider what database are you using?

**Comment by zenspider** [comment]
It's been months... I don't remember... Sorry. Probably pg or sqlite3.

**Comment by gregnavis** [comment]
I'm closing this as I don't know how to reproduce the problem. If you run into it again feel free to reopen.
