### ISSUE TITLE
Task extraneous_indexes crashes on duplicate index

### ISSUE THREAD

**Issue by JDrizzy** [gregnavis/active_record_doctor#7]
A table with two indexes both pointing to the same table column, crashes task `extraneous_indexes`. Example indexes shown below, including error message: 

```sql
CREATE INDEX others_thing_fkey
  ON others
  USING btree
  (thing_id);

CREATE INDEX thing_fkey
  ON others
  USING btree
  (thing_id);
```

```text
NoMethodError: undefined method `name' for nil:NilClass
/ruby-2.2.0/gems/active_record_doctor-1.1.1/lib/active_record_doctor/tasks/extraneous_indexes.rb:39:in `block (2 levels) in extraneous_indexes'
/ruby-2.2.0/gems/active_record_doctor-1.1.1/lib/active_record_doctor/tasks/extraneous_indexes.rb:34:in `map'
/ruby-2.2.0/gems/active_record_doctor-1.1.1/lib/active_record_doctor/tasks/extraneous_indexes.rb:34:in `block in extraneous_indexes'
/ruby-2.2.0/gems/active_record_doctor-1.1.1/lib/active_record_doctor/tasks/extraneous_indexes.rb:24:in `map'
/ruby-2.2.0/gems/active_record_doctor-1.1.1/lib/active_record_doctor/tasks/extraneous_indexes.rb:24:in `extraneous_indexes'
/ruby-2.2.0/gems/active_record_doctor-1.1.1/lib/active_record_doctor/tasks/extraneous_indexes.rb:15:in `run'
/ruby-2.2.0/gems/active_record_doctor-1.1.1/lib/active_record_doctor/tasks/extraneous_indexes.rb:7:in `run'
/ruby-2.2.0/gems/active_record_doctor-1.1.1/lib/tasks/active_record_doctor_tasks.rake:10:in `block (2 levels) in <top (required)>'
```

Great Gem! very helpful. Let me know if you require further details. 
Thanks

**Comment by gregnavis** [comment]
@JDrizzy thanks for kind words and your bug report. The issue has been fixed in master. I'll release a new version this week.
